// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class BPMDataPoint {
  BPMDataPoint({
    this.ts,
    this.bpm,
  });

  String? ts;

  double? bpm;

  List<Object?> _toList() {
    return <Object?>[
      ts,
      bpm,
    ];
  }

  Object encode() {
    return _toList();  }

  static BPMDataPoint decode(Object result) {
    result as List<Object?>;
    return BPMDataPoint(
      ts: result[0] as String?,
      bpm: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BPMDataPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SpeedDataPoint {
  SpeedDataPoint({
    this.ts,
    this.kmh,
    this.paceMinPerKm,
  });

  String? ts;

  double? kmh;

  double? paceMinPerKm;

  List<Object?> _toList() {
    return <Object?>[
      ts,
      kmh,
      paceMinPerKm,
    ];
  }

  Object encode() {
    return _toList();  }

  static SpeedDataPoint decode(Object result) {
    result as List<Object?>;
    return SpeedDataPoint(
      ts: result[0] as String?,
      kmh: result[1] as double?,
      paceMinPerKm: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SpeedDataPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HKWorkoutData {
  HKWorkoutData({
    this.uuid,
    this.start,
    this.end,
    this.distance,
    this.avgSpeed,
    this.avgBPM,
    this.maxBPM,
    this.bpmDataPoints,
    this.speedDataPoints,
  });

  String? uuid;

  String? start;

  String? end;

  double? distance;

  double? avgSpeed;

  double? avgBPM;

  double? maxBPM;

  List<BPMDataPoint?>? bpmDataPoints;

  List<SpeedDataPoint?>? speedDataPoints;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      start,
      end,
      distance,
      avgSpeed,
      avgBPM,
      maxBPM,
      bpmDataPoints,
      speedDataPoints,
    ];
  }

  Object encode() {
    return _toList();  }

  static HKWorkoutData decode(Object result) {
    result as List<Object?>;
    return HKWorkoutData(
      uuid: result[0] as String?,
      start: result[1] as String?,
      end: result[2] as String?,
      distance: result[3] as double?,
      avgSpeed: result[4] as double?,
      avgBPM: result[5] as double?,
      maxBPM: result[6] as double?,
      bpmDataPoints: (result[7] as List<Object?>?)?.cast<BPMDataPoint?>(),
      speedDataPoints: (result[8] as List<Object?>?)?.cast<SpeedDataPoint?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HKWorkoutData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BPMDataPoint) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is SpeedDataPoint) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is HKWorkoutData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return BPMDataPoint.decode(readValue(buffer)!);
      case 130: 
        return SpeedDataPoint.decode(readValue(buffer)!);
      case 131: 
        return HKWorkoutData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HealthKitWorkoutApi {
  /// Constructor for [HealthKitWorkoutApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HealthKitWorkoutApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<HKWorkoutData?>> getWorkouts() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ferum.HealthKitWorkoutApi.getWorkouts$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<HKWorkoutData?>();
    }
  }
}
