// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonErrorAuthHealthKit: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonErrorAuthHealthKit {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class HealthkitAuthorizationPigeonCodecReader: FlutterStandardReader {
}

private class HealthkitAuthorizationPigeonCodecWriter: FlutterStandardWriter {
}

private class HealthkitAuthorizationPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HealthkitAuthorizationPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HealthkitAuthorizationPigeonCodecWriter(data: data)
  }
}

class HealthkitAuthorizationPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HealthkitAuthorizationPigeonCodec(readerWriter: HealthkitAuthorizationPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HealthKitAuthorization {
  /// Demande explicitement l'autorisation HealthKit.
  /// Retourne un Future<bool> en Dart.
  func requestAuthorization(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HealthKitAuthorizationSetup {
  static var codec: FlutterStandardMessageCodec { HealthkitAuthorizationPigeonCodec.shared }
  /// Sets up an instance of `HealthKitAuthorization` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HealthKitAuthorization?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Demande explicitement l'autorisation HealthKit.
    /// Retourne un Future<bool> en Dart.
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ferum.HealthKitAuthorization.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { _, reply in
        api.requestAuthorization { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
  }
}
