// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsworkout(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsworkout(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsworkout(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashworkout(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashworkout(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashworkout(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct WorkoutData: Hashable {
  var type: String? = nil
  var totalDistance: Double? = nil
  var totalEnergyBurned: Double? = nil
  var avgHeartRate: Double? = nil
  var maxHeartRate: Double? = nil
  var avgPace: Double? = nil
  var duration: Double? = nil
  var startDate: String? = nil
  var endDate: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkoutData? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let totalDistance: Double? = nilOrValue(pigeonVar_list[1])
    let totalEnergyBurned: Double? = nilOrValue(pigeonVar_list[2])
    let avgHeartRate: Double? = nilOrValue(pigeonVar_list[3])
    let maxHeartRate: Double? = nilOrValue(pigeonVar_list[4])
    let avgPace: Double? = nilOrValue(pigeonVar_list[5])
    let duration: Double? = nilOrValue(pigeonVar_list[6])
    let startDate: String? = nilOrValue(pigeonVar_list[7])
    let endDate: String? = nilOrValue(pigeonVar_list[8])

    return WorkoutData(
      type: type,
      totalDistance: totalDistance,
      totalEnergyBurned: totalEnergyBurned,
      avgHeartRate: avgHeartRate,
      maxHeartRate: maxHeartRate,
      avgPace: avgPace,
      duration: duration,
      startDate: startDate,
      endDate: endDate
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      totalDistance,
      totalEnergyBurned,
      avgHeartRate,
      maxHeartRate,
      avgPace,
      duration,
      startDate,
      endDate,
    ]
  }
  static func == (lhs: WorkoutData, rhs: WorkoutData) -> Bool {
    return deepEqualsworkout(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashworkout(value: toList(), hasher: &hasher)
  }
}

private class WorkoutPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return WorkoutData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WorkoutPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WorkoutData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WorkoutPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WorkoutPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WorkoutPigeonCodecWriter(data: data)
  }
}

class WorkoutPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WorkoutPigeonCodec(readerWriter: WorkoutPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Workouts {
  func getWorkouts() throws -> [WorkoutData]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WorkoutsSetup {
  static var codec: FlutterStandardMessageCodec { WorkoutPigeonCodec.shared }
  /// Sets up an instance of `Workouts` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Workouts?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getWorkoutsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ferum.Workouts.getWorkouts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWorkoutsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getWorkouts()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getWorkoutsChannel.setMessageHandler(nil)
    }
  }
}
